kubectl delete -f elasticsearch/es-svc.yaml
kubectl delete -f elasticsearch/es-sts.yaml
kubectl delete -f kibana/kibana-deployment.yaml
kubectl delete -f kibana/kibana-svc.yaml
kubectl delete -f fluentd/fluentd-role.yaml
kubectl delete -f fluentd/fluentd-sa.yaml
kubectl delete -f fluentd/fluentd-rb.yaml
kubectl delete -f fluentd/fluentd-ds.yaml
kubectl delete -f test-pod.yaml
